# Generated by Django 2.0.2 on 2018-11-16 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlessection',
            name='sub_title',
            field=models.TextField(default='Nunc rhoncus dui vel sem.', max_length=200),
        ),
        migrations.AlterField(
            model_name='eventssection',
            name='sub_title',
            field=models.TextField(default='Maecenas pulvinar lobortis est. sed accumsan felis. proin risus.', max_length=200),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='text1',
            field=models.CharField(default='Donec posuere metus vitae ipsum. suspendisse potenti.', max_length=200),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='text2',
            field=models.CharField(default='Nulla nisl. morbi quis tortor id nulla ultrices aliquet.', max_length=200),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='text3',
            field=models.CharField(default='In blandit ultrices enim. sed sagittis.', max_length=200),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='title1',
            field=models.CharField(default='In curabitur', max_length=20),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='title2',
            field=models.CharField(default='Quis tempus', max_length=20),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='title3',
            field=models.CharField(default='In non', max_length=20),
        ),
        migrations.AlterField(
            model_name='presentationsection',
            name='sub_title',
            field=models.TextField(default='Proin interdum mauris non ligula pellentesque ultrices.', max_length=200),
        ),
        migrations.AlterField(
            model_name='presentationsection',
            name='text1',
            field=models.TextField(default='Vestibulum sed magna at nunc commodo placerat. mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. integer a nibh. in tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. integer non velit. nulla nisl. pellentesque ultrices mattis odio. cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.', max_length=800),
        ),
        migrations.AlterField(
            model_name='presentationsection',
            name='text2',
            field=models.TextField(default='Aliquam quis turpis eget elit sodales scelerisque. cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. sed accumsan felis. etiam vel augue. quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam. cras in purus eu magna vulputate luctus. maecenas rhoncus aliquam lacus. nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. praesent lectus.', max_length=800),
        ),
        migrations.AlterField(
            model_name='presentationsection',
            name='title',
            field=models.CharField(default='Morbi vel lectus in quam fringilla rhoncus.', max_length=35),
        ),
        migrations.AlterField(
            model_name='promosection',
            name='text',
            field=models.CharField(default='Duis ac nibh. proin interdum mauris non ligula pellentesque ultrices. mauris sit amet eros. quisque porta volutpat erat.', max_length=800),
        ),
        migrations.AlterField(
            model_name='promosection',
            name='title',
            field=models.CharField(default='Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', max_length=35),
        ),
    ]
