# Generated by Django 2.0.2 on 2019-01-02 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20181116_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlessection',
            name='sub_title',
            field=models.TextField(default='Nullam varius. maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. morbi non lectus.', max_length=200),
        ),
        migrations.AlterField(
            model_name='eventssection',
            name='sub_title',
            field=models.TextField(default='Etiam justo. proin at turpis a pede posuere nonummy. in tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', max_length=200),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='text1',
            field=models.CharField(default='Nullam varius. in hac habitasse platea dictumst.', max_length=200),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='text2',
            field=models.CharField(default='Quisque id justo sit amet sapien dignissim vestibulum. nam dui.', max_length=200),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='text3',
            field=models.CharField(default='Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', max_length=200),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='title1',
            field=models.CharField(default='Iaculis turpis', max_length=20),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='title2',
            field=models.CharField(default='Tellus eu', max_length=20),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='title3',
            field=models.CharField(default='Tempor leo', max_length=20),
        ),
        migrations.AlterField(
            model_name='presentationsection',
            name='sub_title',
            field=models.TextField(default='Morbi ut odio. etiam vel augue. donec vitae nisi.', max_length=200),
        ),
        migrations.AlterField(
            model_name='presentationsection',
            name='text1',
            field=models.TextField(default='Vivamus vestibulum sagittis sapien. morbi non quam nec dui luctus rutrum. donec ut mauris eget massa tempor convallis. nam dui. morbi porttitor lorem id ligula. pellentesque at nulla. donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. suspendisse ornare consequat lectus.', max_length=800),
        ),
        migrations.AlterField(
            model_name='presentationsection',
            name='text2',
            field=models.TextField(default='Praesent blandit. in est risus, auctor sed, tristique in, tempus sit amet, sem. fusce consequat. fusce posuere felis sed lacus. in hac habitasse platea dictumst. vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; nulla dapibus dolor vel est. nunc rhoncus dui vel sem. donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. in hac habitasse platea dictumst.', max_length=800),
        ),
        migrations.AlterField(
            model_name='presentationsection',
            name='title',
            field=models.CharField(default='Integer non velit.', max_length=35),
        ),
        migrations.AlterField(
            model_name='promosection',
            name='text',
            field=models.CharField(default='Duis aliquam convallis nunc. praesent blandit. aenean fermentum. morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.', max_length=800),
        ),
        migrations.AlterField(
            model_name='promosection',
            name='title',
            field=models.CharField(default='Duis at velit eu est congue elementum.', max_length=35),
        ),
    ]
