# Generated by Django 2.0.2 on 2018-11-16 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=35)),
                ('sub_title', models.TextField(blank=True, max_length=200, null=True)),
                ('text1', models.TextField(blank=True, max_length=800, null=True)),
                ('text2', models.TextField(blank=True, max_length=800, null=True)),
                ('gallery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='section', to='gallery.Gallery')),
            ],
        ),
    ]
